CREATE TABLE users (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    First_Name VARCHAR(100) NOT NULL,
    Last_Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Gender ENUM('Male', 'Female') NOT NULL,
    Image VARCHAR(255) DEFAULT NULL,
    Title VARCHAR(150) DEFAULT NULL,
    Bio TEXT DEFAULT NULL,
    Major VARCHAR(100) DEFAULT NULL,
    Is_Company TINYINT(1) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    theme VARCHAR(20) DEFAULT 'light',
    PRIMARY KEY (Id)
);
